version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  api:
    image: maven:3.3-jdk-8
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    working_dir: /api
    command: mvn spring-boot:run

  app:
    image: node:latest
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run start